region: eu-west-1
stacks:
  relocation-swagger-ui:
    template-url: templates/aws-s3-template.yml
    parameters:
      bucketName: relocation-swagger-ui
      bucketIndexDocument: internal-api-documentation.html
  relocation-partner-swagger-ui:
    template-url: templates/aws-s3-template.yml
    parameters:
      bucketName: relocation-partner-swagger-ui
      bucketIndexDocument: corporate-partner-documentation.html
      